services:
  db:
    image: mysql
    container_name: db_mysql
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - TZ=America/Sao_Paulo
    ports:
      - "3306:3306"
